name: Deploy Learning app in Vercel plataform

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código fonte
        uses: actions/checkout@v4

      - name: Instalar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Instalar a Vercel CLI
        run: npm install --global vercel@latest

      - name: Puxar as configurações do ambiente Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build do projeto (feito pela própria Vercel CLI)
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy para produção
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}